<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="BASE, Ltd website">
    <meta name="author" content="Hasan Alibegic">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <title>BASE, Ltd.</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,600">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/animate.min.css">
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">
    <!--[if lt IE 9]>
    <script src="/assets/js/html5shiv.js"></script>
    <script src="/assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="loader">
      <div class="fading-line"></div>
    </div>
    <section id="home" class="page">
      <div class="container">
        <div class="content cover text-center">
          <div class="row">
            <div class="col-lg-12" id="greeting">
              <h1 class="animated hiding" data-animation="fadeInDown" data-delay="300">We Are BASE, Ltd.</h1>
              <a class="btn btn-blue nav-external animated hiding" data-animation="fadeIn" data-delay="900" href="#services">Explore</a>
              <h3 class="animated hiding" data-animation="fadeIn" data-delay="600">We're Doing Things Differently.</h3>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div id="navbar-top">
      <nav class="navbar navbar-default navbar-static" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand nav-external" href="#home">BASE, Ltd</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active">
                <a href="#home">Home</a>
              </li>
              <li>
                <a href="#services">Services</a>
              </li>
              <li>
                <a href="#work">Work</a>
              </li>
              <li>
                <a href="#clients">Clients</a>
              </li>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
                <a href="#contact">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <section id="services" class="page">
      <div class="container">
        <div class="content text-center">
          <div class="heading">
            <h2>What we love doing.</h2>
            <div class="border"></div>
            <p>At BASE Ltd our goal is to provide quality results and exceptional service at a competitive price.</p>
          </div>
          <div class="row">
            <div class="col-lg-4 service animated hiding" data-animation="fadeInUp" data-delay="200">
              <i class="fa fa-globe fa-5x"></i>
              <h2>Sound, Stage and Lighting Production</h2>
              <p>Our services range from concert sound systems with complete staging and lighting - to smaller, more intimate sound, stage and/or lighting - to individual equipment rental.</p>
            </div>
            <div class="col-lg-4 service animated hiding" data-animation="fadeInUp" data-delay="400">
              <i class="fa fa-edit fa-5x"></i>
              <h2>Planning and Creative Direction</h2>
              <p>We believe communication is an essential component to the successful planning and outcome of any event.</p>
			  <p>The active communication we have with our clients enables us to openly work with them before, during and after an event with close attention to detail.</p>
            </div>
            <div class="col-lg-4 service animated hiding" data-animation="fadeInUp" data-delay="600">
              <i class="fa fa-crosshairs fa-5x"></i>
              <h2>Professional Engineering Services</h2>
              <p>Our engineers and technicians are equipped with in-depth knowledge and years of experience.</p>
			  <p>The can-do, perfectionist attitude we possess ensures that all intended experience your event to its fullest.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="work" class="page">
      <div class="container">
        <div class="content text-center">
          <div class="heading">
            <h2>This is how we do it.</h2>
            <div class="border"></div>
            <p>We've had the privilege of working with some amazing artists. Here are a few samples of work we've done.</p>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div id="portfolio">
                <ul class="filters list-inline">
                  <li>
                    <a class="active" data-filter="*" href="#">All</a>
                  </li>
                  <li>
                    <a data-filter=".photography" href="#">Mobile Stages</a>
                  </li>
                  <li>
                    <a data-filter=".branding" href="#">Rigging</a>
                  </li>
                  <li>
                    <a data-filter=".web" href="#">Concerts</a>
                  </li>
                </ul>
                <ul class="items list-unstyled clearfix animated hiding" data-animation="fadeInRight">
                  <li class="item branding">
                    <a href="#">
                      <img src="assets/img/work/1.jpg" alt="">
                      <div class="overlay">
                        <span>Rigging</span>
                      </div>
                    </a>
                  </li>
                  <li class="item branding">
                    <a href="#">
                      <img src="assets/img/work/6.jpg" alt="">
                      <div class="overlay">
                        <span>Intimate Concerts</span>
                      </div>
                    </a>
                  </li>
                  <li class="item photography branding">
                    <a href="#">
                      <img src="assets/img/work/7.jpg" alt="">
                      <div class="overlay">
                        <span>Mobile Stages</span>
                      </div>
                    </a>
                  </li>
                  <li class="item photography web">
                    <a href="#">
                      <img src="assets/img/work/9.jpg" alt="">
                      <div class="overlay">
                        <span>Lighting & Effects</span>
                      </div>
                    </a>
                  </li>
                  <li class="item photography">
                    <a href="#">
                      <img src="assets/img/work/2.jpg" alt="">
                      <div class="overlay">
                        <span>College Concerts</span>
                      </div>
                    </a>
                  </li>
                  <li class="item branding web photography">
                    <a href="#">
                      <img src="assets/img/work/3.jpg" alt="">
                      <div class="overlay">
                        <span>Blues Festivals</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/4.jpg" alt="">
                      <div class="overlay">
                        <span>Rock and Roll</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/5.jpg" alt="">
                      <div class="overlay">
                        <span>Stand up Comedy</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/10.jpg" alt="">
                      <div class="overlay">
                        <span>Pop</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/12.jpg" alt="">
                      <div class="overlay">
                        <span>Hip Hop</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/11.jpg" alt="">
                      <div class="overlay">
                        <span>Techno</span>
                      </div>
                    </a>
                  </li>
                  <li class="item web">
                    <a href="#">
                      <img src="assets/img/work/8.jpg" alt="">
                      <div class="overlay">
                        <span>The best part!</span>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="clients" class="page">
	  <div class="container">
        <div class="content text-center">
          <div class="heading">
            <h2>What our Clients say.</h2>
            <div class="border"></div>
		  </div>
		</div>
	  </div>
      <div class="container steel">
        <div class="content text-center">
          <div class="row">
            <div class="col-lg-12 animated hiding" data-animation="fadeInDown">
              <div id="testimonials" class="carousel slide">
                <ol class="carousel-indicators">
                  <li data-target="#testimonials" data-slide-to="0" class="active"></li>
                  <li data-target="#testimonials" data-slide-to="1" class=""></li>
                  <li data-target="#testimonials" data-slide-to="2" class=""></li>
                  <li data-target="#testimonials" data-slide-to="3" class=""></li>
                </ol>
                <div class="carousel-inner">
                  <div class="item active">
                    <p class="quote">The BASE Ltd. team always takes that extra step to make sure an event is done well. It is invaluable to know that I can focus my energy on the other details of our event, and trust that the production set-up will be professional, thorough and always at or above expectation.</p>
                    <p class="client">Joseph F. Maurer - Director of Student Activities, Kenyon College</p>
                  </div>
                  <div class="item">
                    <p class="quote">Great Sound! Thanks.</p>
                    <p class="client">Gary Grainger - Bassist, the Ken Navarro Group</p>
                  </div>
                  <div class="item">
                    <p class="quote">Your work with the CAMF has been superb. I appreciate your creativity and knowledge... Your use of satellite arrays in the artist's market, enhanced the festival atmosphere immensely. Thank you so much for the great work...</p>
                    <p class="client">Barbara Kocab - Festival Coordinator, Whetstone Community Council</p>
                  </div>
                  <div class="item">
                    <p class="quote">Thanks, The guys said your crew did a great job.</p>
                    <p class="client">James "Taco" Martin - VI3 management, E Company Productions</p>
                  </div>
                </div>
                <a class="left carousel-control" data-slide="prev" href="#testimonials">&lsaquo;</a>
                <a class="right carousel-control" data-slide="next" href="#testimonials">&rsaquo;</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="about" class="page">
      <div class="container">
        <div class="content text-center">
          <div class="heading">
            <h2>About Us.</h2>
            <div class="border"></div>
            <p>When we set out, we had a single goal in mind. To provide a top quality experience and exceptional service, setting the bar for concerts and events.</p>
			<p>Today, that original goal remains our core focus. And we've expanded to include complete event logistics, sound, staging, back-line, and creative lighting solutions offering the same exceptional service throughout.</p>
          </div>
          <div class="row">
            <div class="col-md-3 col-md-offset-2 col-sm-5 col-xs-12 teammate animated hiding" data-animation="fadeInLeft" data-delay="300">
              <div class="photo-rounded">
                <img class="img-responsive" src="assets/img/team/1.jpg" alt="">
              </div>
              <div class="bio">
                <h4>Joel Bair</h4>
                <h5>Founder & Lead Systems Tech</h5>
                <div class="border"></div>
                <p>A born technologist and natural leader, Joel has been immersed in the tech field since his youth building transistor amplifiers with his father and toying with op-amps.  With a solid background in electrical engineering and electronics, as well as passion for perfection, he's a key player at every event.</p>
                <ul class="list-inline">
                  <li>
                    <a href="http://www.facebook.com/joel.a.bair" title="Facebook">
                      <i class="fa fa-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/JoelABair" title="Twitter">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://plus.google.com/+JoelBair" title="Google">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 col-md-offset-2 col-sm-5 col-sm-offset-2 col-xs-12 teammate animated hiding" data-animation="fadeInUp" data-delay="600">
              <div class="photo-rounded">
                <img class="img-responsive" src="assets/img/team/2.jpg" alt="">
              </div>
              <div class="bio">
                <h4>Joceline Wojt</h4>
                <h5>Founder & Sales Director</h5>
                <div class="border"></div>
                <p>A passionate event planner and coordinator, Joceline has spent years managing the ground work for great events.  Her deep industry connections and attention to detail are invaluable during the pre- and post-event phase.</p>
                <ul class="list-inline">
                  <li>
                    <a href="http://www.facebook.com/joceline.wojt" title="Facebook">
                      <i class="fa fa-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="http://www.twitter.com/jocelinebair" title="Twitter">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://plus.google.com/100022124736337922703" title="Google">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <div class="twitter text-center">
			<!--	Stub	-->
        </div>
      </div>
    </section>
    <section id="contact" class="page">
      <div class="container">
        <div class="content text-center">
          <div class="heading">
            <h2>Getting in touch.</h2>
            <div class="border"></div>
            <p>Give us a call for a no strings attached quote.  We'll be happy to put everything in writing.</p>
          </div>
          <div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="col-sm-3 col-sm-offset-2 animated hiding" data-animation="fadeInRight" data-delay="200">
					<a href="tel:6145003656">
						<i class="fa fa-phone fa-3x"></i><br>
						1 (614) 500-3656
					</a>
				</div>
				<div class="col-sm-3 col-sm-offset-2 animated hiding" data-animation="fadeInLeft" data-delay="400">
					<i class="fa fa-map-marker fa-3x"></i>
					<address>Columbus, Ohio 43001</ddress>
				</div>
			</div>
          </div>
		</div>
		<div class="content text-center" id="email-section">
		  <script type="text/template" id="email-template">
		  <div class="heading">
			<h2>Send us an email.</h2>
		  </div>
		  <div class="row">
    		<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 animated hiding" data-animation="fadeInDown" data-delay="200">
				<form class="contact" method="POST" action="/send-message" autocomplete="off">
					<input type="hidden" name="_csrf" value="{{csrfToken}}" autocomplete="off">
					<div class="form-group row">
					  <div class="col-sm-5 col-xs-12">
						<input type="text" class="form-control required" id="name" name="name" placeholder="Your Name" autocomplete="off">
					  </div>
					  <div class="col-sm-7 col-xs-12">
						<input type="text" class="form-control" id="organization" name="organization" placeholder="Company or Organization" autocomplete="off">
					  </div>
					</div>
					<div class="form-group row">
						<div class="col-sm-7 col-xs-12">
						<input type="text" class="form-control email required" name="email" placeholder="Email" autocomplete="off">
						</div>
						<div class="col-sm-5 col-xs-12">
						<input type="text" class="form-control phoneUS required" name="phone" placeholder="Phone" autocomplete="off">
						</div>
					</div>
					<div class="form-group row">
						<div class="col-sm-12 col-xs-12">
						  <textarea class="form-control required" name="message" placeholder="Message" autocomplete="off"></textarea>
						</div>
					</div>
					<div class="text-center success" style="display: none">
						<div class="heading">
						  <h1>Thank You!</h1>
						  <h3>Your message has been sent. We'll be in touch soon.</h3>
						</div>
					</div>
					<div class="form-group row">
						<div class="col-sm-12 col-xs-12">
						  <button class="btn btn-default pull-right" data-loading-text="Sending..."  autocomplete="off">Send</button>
						</div>
					</div>
				</form>
			</div>
		  </div>
		  </script>
        </div>
      </div>
    </section>
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 animated hiding" data-animation="fadeInUp">
            <ul class="social list-inline ">
              <li>
                <a class="facebook" href="https://www.facebook.com/pages/BASE-Ltd/111633799461" title="Facebook">
                  <i class="fa fa-facebook-square fa-lg fa-3x"></i>
                </a>
              </li>
              <li>
                <a class="twitter" href="https://twitter.com/BASELtd1" title="Twitter">
                  <i class="fa fa-twitter-square fa-lg fa-3x"></i>
                </a>
              </li>
              <li>
                <a class="google-plus" href="https://plus.google.com/u/0/+BaseltdBiz" title="Google+">
                  <i class="fa fa-google-plus-square fa-lg fa-3x"></i>
                </a>
              </li>
              <li>
                <a class="linkedin" href="http://www.linkedin.com/companies/386870/BASE,+Ltd" title="LinkedIn">
                  <i class="fa fa-linkedin-square fa-lg fa-3x"></i>
                </a>
              </li>
            </ul>
            <p class="copyright">
              Created by BASE, Ltd. &middot;
              Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a> &middot;
              Powered by <a href="http://getbootstrap.com/">Bootstrap</a>
            </p>
          </div>
        </div>
      </div>
    </footer>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/isotope.pkgd.min.js"></script>
    <script src="/assets/js/imagesloaded.min.js"></script>
    <script src="/assets/js/jquery.scrollTo.min.js"></script>
    <script src="/assets/js/jquery.nav.min.js"></script>
    <script src="/assets/js/jquery.appear.min.js"></script>
    <script src="/assets/jquery-validation-1.12.0/lib/jquery.form.js"></script>
    <script src="/assets/jquery-validation-1.12.0/dist/jquery.validate.min.js"></script>
    <script src="/assets/jquery-validation-1.12.0/dist/additional-methods.min.js"></script>
    <script src="/assets/js/script.js"></script>

	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-24419831-1']);
		_gaq.push(['_trackPageview']);

		(function() {
		  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
  </body>
</html>
